### ISSUE TITLE
Errors on mac

### ISSUE THREAD

**Issue by nikola8** [soulisalmed/biff#10]
I see these errors on the latest MacOS:

`(venv) sh-3.2# python -m biff anwar2009.pdf
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/keyboard/Documents/extract pdf highligh/biff-master/biff/biff.py", line 21, in <module>
    from fitz import open as fitzopen
ModuleNotFoundError: No module named 'fitz'
(venv) sh-3.2# 
`

**Comment by joaoponceleao** [comment]
Fitz belongs to PyMuPDF. You may need to reinstall it.
